### ISSUE TITLE
Release 6.0.2

### ISSUE THREAD

**Issue by hipstersmoothie** [octokit/endpoint.js#139]
trying to upgrade lerna to v17 and this is the last thing that depends on old types (I think)

https://github.com/lerna/lerna/pull/2600

**Comment by gr2m** [comment]
I'm looking into it

**Comment by gr2m** [comment]
should be fixed soon via #140. 

I had to migrate from Greenkeeper to Dependabot recently, and dependabot does not set the commit prefixes correctly for out-of-range production dependency updates yet. I've build my own little workaround script for that, but only after 41d47f5, and there was no release since. Sorry for that
